test = {   'name': 'q4_4',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> callable(mean_values)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> import numbers;\n>>> isinstance(mean_values('France'), float) or isinstance(mean_values('France'), numbers.Integral)\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
