test = {   'name': 'q2_9',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': ">>> import numbers;\n>>> isinstance(year_containing_peak_trips, numbers.Integral) # Make sure you're returning a year as your answer!\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> 2012 < year_containing_peak_trips < 2020\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
