test = {   'name': 'q3_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> import numbers;\n>>> isinstance(earnings_prop, numbers.Real)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= earnings_prop <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> with_earnings.shape\n(10125, 8)', 'hidden': False, 'locked': False},
                                   {'code': ">>> 'earnings' in with_earnings.columns\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> with_earnings.get('earnings').iloc[0] == 13_001\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
